ALTER TABLE clients ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT '';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS followers INT DEFAULT 0;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS following INT DEFAULT 0;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS profile_photo TEXT DEFAULT '';
